insert into language(name) values('hun');
insert into language(name) values('eng');
insert into topic(name, language_id) values('culture',2);
insert into word(word_name, language_id) values('elevenses',2);
insert into word(word_name, language_id) values('tízórai',1);
insert into word(word_name, language_id) values('supper',2);
insert into word(word_name, language_id) values('könnyű vacsora',1);
insert into word(word_name, language_id) values('the least',2);
insert into word(word_name, language_id) values('a legkevesebbet',1);
insert into word(word_name, language_id) values('course',2);
insert into word(word_name, language_id) values('fogás',1);
insert into word(word_name, language_id) values('pork',2);
insert into word(word_name, language_id) values('disznóhús',1);
insert into word(word_name, language_id) values('beef',2);
insert into word(word_name, language_id) values('marhahús',1);
insert into word(word_name, language_id) values('veal',2);
insert into word(word_name, language_id) values('bárányhús',1);
insert into word(word_name, language_id) values('duck',2);
insert into word(word_name, language_id) values('kacsa',1);
insert into word(word_name, language_id) values('turkey',2);
insert into word(word_name, language_id) values('pulyka',1);
insert into word(word_name, language_id) values('dish',2);
insert into word(word_name, language_id) values('étel',1);
insert into word(word_name, language_id) values('lentil',2);
insert into word(word_name, language_id) values('lencse',1);
insert into word(word_name, language_id) values('noodles',2);
insert into word(word_name, language_id) values('kifőtt tészta',1);
insert into word(word_name, language_id) values('cottage cheese',2);
insert into word(word_name, language_id) values('túró',1);
insert into word(word_name, language_id) values('pancake',2);
insert into word(word_name, language_id) values('palacsinta',1);
insert into word(word_name, language_id) values('national dish',2);
insert into word(word_name, language_id) values('nemzeti étel',1);
insert into word(word_name, language_id) values('sour cream',2);
insert into word(word_name, language_id) values('tejföl',1);
insert into word(word_name, language_id) values('stuffed cabbage',2);
insert into word(word_name, language_id) values('töltöttkáposzta',1);
insert into word(word_name, language_id) values('left-over',2);
insert into word(word_name, language_id) values('maradék',1);
insert into word(word_name, language_id) values('cold cuts',2);
insert into word(word_name, language_id) values('hideg felvágott',1);
insert into translation_entry(word1_id, word2_id,topic_id) values(1,2,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(3,4,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(5,6,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(7,8,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(9,10,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(11,12,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(13,14,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(15,16,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(17,18,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(19,20,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(21,22,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(23,24,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(25,26,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(27,28,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(29,30,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(31,32,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(33,34,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(35,36,1);
insert into translation_entry(word1_id, word2_id,topic_id) values(37,38,1);



